[tool.poetry]
name = "ucpd-incident-scraper"
version = "0.1.0"
description = "This code is going to be used to scrape the UCPD Daily Incident every day and store the incidents on a generic JSON data-store through the use of a Python üêç job on GCP's Cloud Run."
authors = ["michplunkett"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
lxml = "^4.9.3"
pytz = "^2023.3"
censusgeocode = "^0.5.2"
cssselect = "^1.2.0"
google-cloud-ndb = "^2.1.1"
google-cloud-logging = "^3.6.0"
flask = "^2.3.3"
gunicorn = "^21.2.0"
apscheduler = "^3.10.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.281"
isort = "^5.12.0"
black = "^23.7.0"

[tool.black]
line-length = 80

[tool.isort]
profile= "black"
line_length = 80
skip = [".gitignore", "project/data/"]

[tool.ruff]
fix=true
line-length = 80
target-version = "py311"
select = ["D"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["D104"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
